spring:
  datasource:
    url: jdbc:mysql://119.29.214.244:3306/bysj?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: zhenxin
    password: 123456
  druid:
  #连接池的配置信息119.29.214.244
  ## 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    ## 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  data:
#    elasticsearch:
#      cluster-name: my-application
#      cluster-nodes: localhost:9300
mybatis:
  type-aliases-package: com.depth.management.model
  mapperLocations: "classpath:mapper/*.xml"
  config-location: "classpath:mybatis-config.xml"
logging:
  level:
    com:
      depth:
        management:
          mapper: debug
  file: logs/management.log
server:
  port: 8089

